function Hd = lpf2
%LPF2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.2 and the Signal Processing Toolbox 6.20.
% Generated on: 14-Apr-2014 15:44:27

% FIR maximally flat Lowpass filter designed using the MAXFLAT function.

% All frequency values are in Hz.
Fs = 44100;  % Sampling Frequency

N  = 8;    % Order
Fc = 2000;  % Cutoff Frequency

%% Calculate the second-order sections coefficients to avoid round-off
%errors.
[b,a,b1,b2,sos_var,g] = maxflat(N, 'sym', Fc/(Fs/2));
Hd                    = dfilt.df2sos(sos_var, g);

% [EOF]
