function Hd = lpf(N,fc,alfa)
%LPF Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.2 and the Signal Processing Toolbox 6.20.
% Generated on: 10-Apr-2014 12:36:00

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
if(nargin <3)
    alfa = 2.5;
end

Fs = 44100;  % Sampling Frequency

N    = N;      % Order
Fc   = fc;    % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = gausswin(N+1,alfa);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
